"""Initial migration

Revision ID: 329c7eee936b
Revises: 
Create Date: 2025-07-25 23:41:19.927055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329c7eee936b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_id', sa.String(), nullable=False),
    sa.Column('jira_key', sa.String(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ticket_type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REOPENED', name='ticketstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOWEST', 'LOW', 'MEDIUM', 'HIGH', 'HIGHEST', name='ticketpriority'), nullable=True),
    sa.Column('assignee_email', sa.String(), nullable=True),
    sa.Column('assignee_name', sa.String(), nullable=True),
    sa.Column('reporter_email', sa.String(), nullable=True),
    sa.Column('reporter_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.Column('similar_tickets', sa.Text(), nullable=True),
    sa.Column('code_analysis', sa.Text(), nullable=True),
    sa.Column('title_embedding', sa.Text(), nullable=True),
    sa.Column('description_embedding', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('sync_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assignee_email'), 'tickets', ['assignee_email'], unique=False)
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_jira_id'), 'tickets', ['jira_id'], unique=True)
    op.create_index(op.f('ix_tickets_jira_key'), 'tickets', ['jira_key'], unique=True)
    op.create_index(op.f('ix_tickets_project_key'), 'tickets', ['project_key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('microsoft_user_id', sa.String(), nullable=True),
    sa.Column('teams_user_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_preferences', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_microsoft_user_id'), 'users', ['microsoft_user_id'], unique=True)
    op.create_index(op.f('ix_users_teams_user_id'), 'users', ['teams_user_id'], unique=True)
    op.create_table('integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('integration_type', sa.Enum('JIRA', 'CONFLUENCE', 'GITHUB', 'GITLAB', 'AZURE_DEVOPS', name='integrationtype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('encrypted_token', sa.Text(), nullable=True),
    sa.Column('oauth_token', sa.Text(), nullable=True),
    sa.Column('oauth_refresh_token', sa.Text(), nullable=True),
    sa.Column('oauth_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_table('project_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jira_project_key', sa.String(), nullable=False),
    sa.Column('jira_project_name', sa.String(), nullable=False),
    sa.Column('jira_project_id', sa.String(), nullable=False),
    sa.Column('git_provider', sa.String(), nullable=False),
    sa.Column('git_organization', sa.String(), nullable=False),
    sa.Column('git_repository', sa.String(), nullable=False),
    sa.Column('git_branch', sa.String(), nullable=True),
    sa.Column('git_repository_id', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='mappingconfidence'), nullable=True),
    sa.Column('mapping_algorithm', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('matching_factors', sa.Text(), nullable=True),
    sa.Column('alternative_mappings', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('verified_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_mappings_id'), 'project_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_project_mappings_jira_project_key'), 'project_mappings', ['jira_project_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_mappings_jira_project_key'), table_name='project_mappings')
    op.drop_index(op.f('ix_project_mappings_id'), table_name='project_mappings')
    op.drop_table('project_mappings')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_users_teams_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_microsoft_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tickets_project_key'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_jira_key'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_jira_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assignee_email'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###